### ISSUE TITLE
Plug-in not working

### ISSUE THREAD

**Issue by zsihalla** [weijia/tabby-quick-cmds-buttons#1]
Whenever opening Tabby after downloading plug-in I am receiving this error messege:

_TypeError: Cannot read properties of undefined (reading 'qc')_

**Comment by whollaus** [comment]
I can confirm this. Does not work for me too.

**Comment by stiw47** [comment]
+1 confirmation. 

In plugin description, it is stated: _An plugin that create buttons for quick commands, need to install quick-cmds and add commands first, based on Eugene Pankov's tabby-clippy._
But even that I have `quick-cmds` installed, it is fully working, and I added two commands and saved them, below is behavior every time I start the Tabby, if `quick-cmds-buttons` is enabled:

![image](https://github.com/weijia/tabby-quick-cmds-buttons/assets/3337416/c83ccacc-08ee-4f70-a6a4-ccb9f74b5128)

Please let me know if I can help with providing some log or if something additionally needs to be installed. My OS is Windows 11 Pro, 22H2.

![image](https://github.com/weijia/tabby-quick-cmds-buttons/assets/3337416/d4f5d9fb-11a6-4612-8e24-0fdda31619c9)

![image](https://github.com/weijia/tabby-quick-cmds-buttons/assets/3337416/d4dbbf35-6585-4dba-9a5c-3c173f503791)

**Comment by fthrsya** [comment]
+1 
![image](https://github.com/weijia/tabby-quick-cmds-buttons/assets/13959011/201081b5-baba-46b8-ac96-fd1a52f566ff)

this error solve please

**Comment by weijia** [comment]
Hi, sorry, I was handling some personal issues recently. Now I added a new version, could you please try if it is working now?

**Comment by fthrsya** [comment]
yes, resolved on MacOS thank you

**Comment by stiw47** [comment]
Jupiiiiiiii, it is working.

Few things....

1. No need to say "sorry", you are doing this in your spare time I guess and thank you for that
2. Since your plugin is based on Clippy, it seems they are "working together" somehow. E.g. I also have Clippy installed. If I choose either your plugin or Clippy in left panel of settings, both will be selected, lol. Also, your plugin has Clippy menu, and starting by changing item in Clippy menu, so I guess this was intentional.

![image](https://github.com/weijia/tabby-quick-cmds-buttons/assets/3337416/30bf5cd4-cf8a-4932-965a-f0eed813d210)

Toggle it from context menu is not working, but this is buggy for Clippy as well in my case.

![image](https://github.com/weijia/tabby-quick-cmds-buttons/assets/3337416/77c0b9c3-3d6f-4262-9034-dc5ae013bd73)

Thank you once again.

**Comment by weijia** [comment]
> Jupiiiiiiii, it is working.
> 
> Few things....
> 
> 1. No need to say "sorry", you are doing this in your spare time I guess and thank you for that
> 2. Since your plugin is based on Clippy, it seems they are "working together" somehow. E.g. I also have Clippy installed. If I choose either your plugin or Clippy in left panel of settings, both will be selected, lol. Also, your plugin has Clippy menu, and starting by changing item in Clippy menu, so I guess this was intentional.
> 
> ![image](https://user-images.githubusercontent.com/3337416/268023917-30bf5cd4-cf8a-4932-965a-f0eed813d210.png)
> 
> Toggle it from context menu is not working, but this is buggy for Clippy as well in my case.
> 
> ![image](https://user-images.githubusercontent.com/3337416/268024609-77c0b9c3-3d6f-4262-9034-dc5ae013bd73.png)
> 
> Thank you once again.

Hi, yes, it's based on Clippy and I didn't have time yet to create a fully standalone extension. Thanks for the screenshots. I'll try to fix this when I have time. And anyone is welcome to raise pull request as well. :)
